using System;
using UnityEngine;

/// <summary>
/// Loads manually adjustable built-in prop prefabs from Resources.
/// The prefabs are generated by BuiltInPropPrefabBuilder in the Unity Editor.
/// </summary>
public static class BuiltInPropLibrary
{
    public static GameObject Create(string propName, Transform parent, Vector3 localPosition, float yawDegrees)
    {
        if (!BuiltInPropCatalog.IsBuiltIn(propName))
        {
            return null;
        }

        GameObject prefab = Resources.Load<GameObject>(BuiltInPropCatalog.ResourcePath(propName));
        if (prefab == null)
        {
            return null;
        }

        GameObject root = new GameObject(propName.Trim());
        root.transform.SetParent(parent, false);
        root.transform.localPosition = localPosition;
        root.transform.localRotation = Quaternion.Euler(0f, yawDegrees, 0f);

        GameObject instance = UnityEngine.Object.Instantiate(prefab, root.transform, false);
        instance.name = prefab.name + "_Visual";
        instance.transform.localPosition = Vector3.zero;
        instance.transform.localRotation = Quaternion.identity;
        instance.transform.localScale = Vector3.one;

        if (!TryCalculateBounds(instance.transform, out Bounds bounds))
        {
            DestroyObject(root);
            return null;
        }

        // Preserve the manually authored X/Z offset and orientation, but always ensure
        // that the final object rests on the runtime tabletop.
        instance.transform.position += Vector3.up * (root.transform.position.y - bounds.min.y);
        EnableShadows(instance);

        if (TryCalculateBounds(instance.transform, out Bounds finalBounds))
        {
            ContactShadowUtility.EnsureContactShadow(root.transform, finalBounds, root.transform.position.y);
        }

        return root;
    }

    private static bool TryCalculateBounds(Transform root, out Bounds bounds)
    {
        bool initialized = false;
        bounds = new Bounds(root != null ? root.position : Vector3.zero, Vector3.zero);
        if (root == null)
        {
            return false;
        }

        foreach (Renderer renderer in root.GetComponentsInChildren<Renderer>(true))
        {
            if (renderer == null || string.Equals(renderer.name, "ContactShadow", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            if (renderer is MeshRenderer)
            {
                MeshFilter filter = renderer.GetComponent<MeshFilter>();
                if (filter == null || filter.sharedMesh == null)
                {
                    continue;
                }
            }
            else if (renderer is SkinnedMeshRenderer skinned && skinned.sharedMesh == null)
            {
                continue;
            }

            if (!initialized)
            {
                bounds = renderer.bounds;
                initialized = true;
            }
            else
            {
                bounds.Encapsulate(renderer.bounds);
            }
        }

        return initialized && bounds.size.sqrMagnitude > 0.0000000001f;
    }

    private static void EnableShadows(GameObject instance)
    {
        foreach (Renderer renderer in instance.GetComponentsInChildren<Renderer>(true))
        {
            renderer.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.On;
            renderer.receiveShadows = true;
        }
    }

    private static void DestroyObject(GameObject target)
    {
        if (target == null)
        {
            return;
        }

        if (Application.isPlaying)
        {
            UnityEngine.Object.Destroy(target);
        }
        else
        {
            UnityEngine.Object.DestroyImmediate(target);
        }
    }
}
